### ISSUE TITLE
drop down menu doesn't work

### ISSUE THREAD

**Issue by rschaer** [absalomedia/grav-theme-future#6]
As the title says, I can't get the drop-down menu to work with the Future theme. On some formats/resolutions the site will readjust and remove top level navigation, meaning it becomes unusable without a working drop-down menu to access the different pages. Menu is enabled in theme selection.

**Comment by agentirons** [comment]
Hey @rschaer, on the off-chance you still need it (I added a pull request for @absalomedia as well):

The solution is to add the following under the `<nav class="main">` block in `themes/future/templates/partials/base.html.twig`:

`<section id="menu">
  
    <section>
      <ul class="links">
      {% for page in pages.children %}
          {% if page.visible %}
              {% set current_page = (page.active or page.activeChild) ? 'current' : '' %}
                  <li>
                      <a href="{{ page.url }}">
                          <h3>{{ page.menu }}</h3>
                      </a>
                  </li>
          {% endif %}
      {% endfor %}
      {# CUSTOM MENU ITEMS #}
      {% for mitem in site.menu %}
          <li>
              <a href="{{ mitem.link }}">
                <h3>{{ mitem.text }}</h3>
              </a>
          </li>
      {% endfor %}
      </ul>
    </section>
</section>`

I dug through HTML5UP's original [Future Imperfect](https://html5up.net/future-imperfect) template in order to figure out that the `<section id="menu">` block was missing entirely from grav-theme-future.

**Comment by absalomedia** [comment]
Fixed in 1.0.8 release with @agentirons help

**Comment by rschaer** [comment]
Very cool, will revisit my project that was going to use this theme soon :)
